Use temurin 8 docker image
jenkins-infra/ircbot pull request #120
Opened 2022-10-12 21:53 UTC by NotMyFault

I can't locate the current image on the docker hub, the change proposed uses temurin builds.

2022-10-12 21:57 UTC, slide approved these changes
We should look at upgrading to at least Java 11 at some point.

2022-10-12 22:00 UTC, NotMyFault commented
> We should look at upgrading to at least Java 11 at some point.

Every project, that invokes the Jenkins Jira API is a nightmare to upgrade 🥴

2022-10-12 22:04 UTC, timja commented
> > We should look at upgrading to at least Java 11 at some point.
> 
> Every project, that invokes the Jenkins Jira API is a nightmare to upgrade 🥴

Ha yup I've hit that before, generally you can drop that dep and use the client directly but the atlassian client isn't great.
From memory they switch from Jax-WS to REST at some point but I wasn't able to figure out how to port some functionality in the last project I tried this in, (rpu maybe?)

2022-10-12 22:11 UTC, NotMyFault commented
Yeah, also used for the RPU, but hey, after my changes today, the RPU's minimum Java version is now Java 11 👏🏻

2022-10-12 22:14 UTC, NotMyFault commented
Requested your review, slide's doesn't suffice to merge this pr.

2022-10-13 07:06 UTC, dduportal requested changes
Good idea ! 

We must stick to a JRE (as it is a production image)

2022-10-13 07:06 UTC, dduportal commented on Dockerfile
> +FROM eclipse-temurin:8-alpine
```suggestion
# TODO: Bump to JDK11 and generate a JRE with jlink - https://hub.docker.com/_/eclipse-temurin#CreatingaJREusingjlink
FROM eclipse-temurin:8-jre-alpine
```

- The image is aimed at running in a production environment so no JDK at all. 
- Add a note for later JDK11 user to generate a JRE with jlink (like what we do on jenkinsci/docker)

2022-10-13 07:14 UTC, timja approved these changes

2022-10-13 07:16 UTC, dduportal approved these changes
nice job!

2022-10-13 07:16 UTC, merged